apiVersion: v1
kind: InstallConfig
baseDomain: baremetal.rr5.labs
compute:
 - name: worker
   replicas: 3
controlPlane:
   name: master
   platform: {}
   replicas: 3
metadata:
   name: cluster  
networking:
  clusterNetworks:
  - cidr: 10.128.0.0/14
    hostPrefix: 23
  networkType: OpenShiftSDN
  serviceNetwork:
  - 172.30.0.0/16
platform:
   none: {}
   apiVIP: 192.168.111.53        
   ingressVIP: 192.168.111.52 
   dnsVIP: 192.168.111.51 
   hosts:
      # Master nodes are always RHCOS
      - name: master-0
        role: master
        bmc:
           address: ipmi://172.16.144.202 
           credentialsName: poweredge-lab-ipmi 
        bootMACAddress: 1C:34:DA:50:C1:B1
        sdnMacAddress: 1C:34:DA:49:04:48
        hardwareProfile: default
        osProfile: 
           type: rhcos
           pxe: uefi
           install_dev: sda  
      - name: master-1
        role: master
        bmc:
           address: ipmi://172.16.144.203
           credentialsName: poweredge-lab-ipmi
        bootMACAddress: 1C:34:DA:50:C2:09
        sdnMacAddress: 1C:34:DA:49:0F:E0
        hardwareProfile: default
        osProfile:
           type: rhcos
           pxe: uefi
           install_dev: sda
      - name: master-2
        role: master
        bmc:
           address: ipmi://172.16.144.204
           credentialsName: poweredge-lab-ipmi
        bootMACAddress: B8:59:9F:15:86:FD
        sdnMacAddress: 1C:34:DA:49:11:A0
        hardwareProfile: default
        osProfile:
           type: rhcos
           pxe: uefi
           install_dev: sda
      - name: worker-0
        role: worker
        bmc: 
           address: ipmi://172.16.144.205
           credentialsName: poweredge-lab-ipmi
        bootMACAddress: 1C:34:DA:50:C0:49
        sdnMacAddress: 1C:34:DA:49:04:58
        hardwareProfile: default
        osProfile: 
           type: rhcos
           pxe: uefi    
           install_dev: sda  
      - name: worker-1
        role: worker
        bmc: 
           address: ipmi://172.16.144.206
           credentialsName: poweredge-lab-ipmi
        bootMACAddress: B8:59:9F:15:87:55
        sdnMacAddress: 1C:34:DA:49:0F:B8
        hardwareProfile: default
        osProfile: 
           type: rhcos
           pxe: uefi
           install_dev: sda  
      - name: worker-2
        role: worker
        bmc: 
           address: ipmi://172.16.144.207
           credentialsName: poweredge-lab-ipmi
        bootMACAddress: 1C:34:DA:4B:50:9D
        sdnMacAddress: 1C:34:DA:49:09:D8
        hardwareProfile: default
        osProfile: 
           type: rhcos
           pxe: uefi
           install_dev: sda  
pullSecret: 'PULL_SECRET'  
sshKey: |
   SSH_PUB_KEY
