apiVersion: kni.akraino.org/v1alpha1
kind: SiteConfig
metadata:
  name: notImportantHere
config: {}
provisioningInfrastructure:
  hosts:
    masterBootInterface: eno2
    workerBootInterface: eno2
    masterSdnInterface: ens1f0
    workerSdnInterface: ens1f0

  network:
    provisioningIpCidr: 172.16.102.0/24 
    provisioningDHCPStart: 172.16.102.101
    provisioningDHCPEnd: 172.16.102.150 
    baremetalIpCidr: 192.168.111.0/24
    baremetalDHCPStart: 192.168.111.101
    baremetalDHCPEnd: 192.168.111.150
    baremetalGWIP: 192.168.111.2
    dns:
      cluster: 192.168.111.200
      external1: 8.8.8.8

  provHost:
    interfaces:
      provisioning: em2 
      provisioningIpAddress: 172.16.102.100
      baremetal: p1p1
      baremetalIpAddress: 192.168.111.100
      external: em1
    bridges:
      provisioning: provisioning 
      baremetal: baremetal
    services:
      baremetalDHCP: true 
      clusterDNS: true 
      baremetalGateway: false
