apiVersion: kni.akraino.org/v1alpha1
kind: SiteConfig
metadata:
  name: notImportantHere
config: {}
provisioningInfrastructure:
  hosts:
    masterBootInterface: eno1
    workerBootInterface: eno1
    masterSdnInterface: eno2
    workerSdnInterface: eno2

  network:
    provisioningIpCidr: 192.168.112.0/24 
    provisioningDHCPStart: 192.168.112.101
    provisioningDHCPEnd: 192.168.112.150 
    baremetalIpCidr: 192.168.111.0/24
    baremetalDHCPStart: 192.168.111.101
    baremetalDHCPEnd: 192.168.111.150
    baremetalGWIP: 192.168.111.2
    dns:
      cluster: 192.168.111.200
      external1: 8.8.8.8

  provHost:
    interfaces:
      provisioning: em2 
      provisioningIpAddress: 192.168.112.100
      baremetal: em1
      baremetalIpAddress: 192.168.111.100
      external: p1p1
    bridges:
      provisioning: provisioning 
      baremetal: baremetal
    services:
      baremetalDHCP: true 
      clusterDNS: true 
      baremetalGateway: false
